version: '3.4'

networks:
    backendforpunkapi:
    

services:
  sql-db:
    container_name: authentication-service-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa$$w0rd2023 
    networks:
      - backendforpunkapi
  backendforpunkapi:
    container_name: authentication-service
    image: ${DOCKER_REGISTRY-}backendforpunkapi
    build:
      context: .
      dockerfile: BackendForPunkApi/Dockerfile
    ports: 
     -  8001:80
    depends_on:
     - sql-db
    environment:
      - DB_HOST=sql-db
      - DB_NAME=EComerceOnContainers
      - DB_SA_PASSWORD=Pa$$w0rd2023

    networks:
      - backendforpunkapi
